name: Ejecutar ETL

on:
  push:
    branches:
      - main

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install pandas sqlalchemy psycopg2-binary

      - name: Ejecutar ETL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python ETL/etl.py
